image: gitpod/workspace-postgres
tasks:
  - init: > 
      cp .vscode/launch_gitpod.json .vscode/launch.json &&
      pip install pytest &&
      pip install -r lib/galaxy/dependencies/dev-requirements.txt &&
      make client
  - command: cp config/galaxy.yml.sample config/galaxy.yml
  - command: make client-watch
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
vscode:
  extensions:
    - ms-python.vscode-pylance
