tasks:
  - init: > 
      ln -s .vscode/settings_gitpod.json .vscode/settings.json &&
      ln -s .vscode/launch_gitpod.json .vscode/launch.json &&
      pip install -r lib/galaxy/dependencies/dev-requirements.txt && 
      make client
  - command: cp config/galaxy.yml.sample config/galaxy.yml
  - command: make client-watch
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
vscode:
  extensions:
    - ms-python.python
