os: osx
# No version of Python is available via virtualenv on OS X workers, see https://github.com/travis-ci/travis-ci/issues/2312
language: generic
sudo: required

env:
  - TOX_ENV=py27-first_startup
  - TOX_ENV=py35-first_startup

before_install:
  # Install Singularity
  - sudo apt install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools wget git
  - wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
  - echo 'export GOPATH=${HOME}/go' >> ~/.bashrc
  - echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc
  - source ~/.bashrc
  - mkdir -p $GOPATH/src/github.com/sylabs
  - cd $GOPATH/src/github.com/sylabs
  - git clone https://github.com/sylabs/singularity.git
  - cd singularity
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - cd $GOPATH/src/github.com/sylabs/singularity
  - ./mconfig
  - make -C builddir
  - sudo make -C builddir install

install:
  - set -e
  - pip install tox
  - |
    if [ "$TOX_ENV" == "py27-first_startup" ]; then
        sh scripts/common_startup.sh
        wget -q https://github.com/jmchilton/galaxy-downloads/raw/master/db_gx_rev_0127.sqlite
        mv db_gx_rev_0127.sqlite database/universe.sqlite
        sh manage_db.sh -c ./config/galaxy.yml.sample upgrade
    elif [ "$TOX_ENV" == "py35-first_startup" ]; then
        MINICONDA_URL="https://repo.anaconda.com/miniconda"
        MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
        curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
        bash $MINICONDA_FILE -b
        ~/miniconda3/bin/conda create --yes --override-channels --channel conda-forge --channel defaults --name _galaxy_ 'python=3.5' 'pip>=9' 'virtualenv>=16'
        . ~/miniconda3/bin/activate _galaxy_
    fi

script: tox -e $TOX_ENV

notifications:
  email: false
