apiVersion: v1
kind: Service
metadata:
  name: testing-service
  labels:
    app: testing
spec:
  ports:
  - port: 5432
    name: postgres
  - port: 5672
    name: rabbitmq
  type: NodePort 
  selector:
    app: testing
