name: Integration
on: [push, pull_request]
env:
  GALAXY_TEST_DBURI: 'postgresql://postgres:postgres@localhost:5432/galaxy?client_encoding=utf8'
  GALAXY_TEST_AMQP_URL: 'amqp://localhost:5672//'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7']
        subset: ['not (upload_datatype or extended_metadata or kubernetes)']
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'galaxy root'
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip dir
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('galaxy root/requirements.txt') }}
      - name: Run tests
        if: matrix.subset != 'kubernetes'
        run: './run_tests.sh -integration test/integration/test_interactivetools_api.py -- -s InteractiveToolsIntegrationTestCase'
        working-directory: 'galaxy root'
      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Integration test results (${{ matrix.python-version }}, ${{ matrix.subset }})
          path: 'galaxy root/run_integration_tests.html'
